-- Seed data for a fresh gis-db. INSERT OR IGNORE: existing rows are never changed;
-- to rename projects/layers on a live database run derived/004-rename-projects.sql.
INSERT OR IGNORE INTO projects (slug, title_en, title_fr, desc_en, desc_fr, category, year, color, visible, collapsed, sort_order, published) VALUES ('something-open-ground', 'Tungsten Open Ground — Yukon', 'Terrains libres tungstène — Yukon', 'Prospectivity screening for tungsten skarn targets: regional faults, favorable geology units and MINFILE occurrences, built on Yukon Geological Survey open data.', 'Analyse de prospectivité pour des cibles de skarn à tungstène : failles régionales, unités géologiques favorables et indices MINFILE, à partir des données ouvertes de la Commission géologique du Yukon.', 'Mineral Exploration', '2025', '#F0B429', 1, 1, 1, 1);
INSERT OR IGNORE INTO layers (project_id, slug, label_en, label_fr, r2_key, style_json, fields_json, visible, published, sort_order, feature_count, byte_size) VALUES ((SELECT id FROM projects WHERE slug = 'something-open-ground'), 'faults', 'Regional faults (YGS)', 'Failles régionales (YGS)', 'geojson/something-open-ground/faults.geojson', '{"weight": 1.2, "dash": "6 4"}', '[]', 1, 1, 1, 34826, 7119504);
INSERT OR IGNORE INTO layers (project_id, slug, label_en, label_fr, r2_key, style_json, fields_json, visible, published, sort_order, feature_count, byte_size) VALUES ((SELECT id FROM projects WHERE slug = 'something-open-ground'), 'favorable-geology', 'Favorable geology', 'Géologie favorable', 'geojson/something-open-ground/favorable-geology.geojson', '{}', '["FID", "SHAPE_Area", "SHAPE_Leng"]', 1, 1, 2, 149, 1423201);
INSERT OR IGNORE INTO layers (project_id, slug, label_en, label_fr, r2_key, style_json, fields_json, visible, published, sort_order, feature_count, byte_size) VALUES ((SELECT id FROM projects WHERE slug = 'something-open-ground'), 'ocurrences', 'MINFILE occurrences', 'Indices MINFILE', 'geojson/something-open-ground/ocurrences.geojson', '{}', '["ALIAS", "FID", "X", "Y"]', 1, 1, 3, 65, 29833);
INSERT OR IGNORE INTO projects (slug, title_en, title_fr, desc_en, desc_fr, category, year, color, visible, collapsed, sort_order, published) VALUES ('urban-digitize', 'Urban Digitization', 'Numérisation urbaine', 'High-precision digitization of buildings, roads, pavements, cycleways and road markings from drone imagery.', 'Numérisation de haute précision des bâtiments, routes, revêtements, pistes cyclables et marquages au sol à partir d''imagerie drone.', 'Cartography', '2025', '#e90eda', 1, 1, 2, 1);
INSERT OR IGNORE INTO layers (project_id, slug, label_en, label_fr, r2_key, style_json, fields_json, visible, published, sort_order, feature_count, byte_size) VALUES ((SELECT id FROM projects WHERE slug = 'urban-digitize'), 'buildings', 'Buildings', 'Bâtiments', 'geojson/urban-digitize/buildings.geojson', '{"color": "#fe221b94", "outerColor": "#36f029"}', '["FID", "id"]', 1, 1, 1, 39, 26362);
INSERT OR IGNORE INTO layers (project_id, slug, label_en, label_fr, r2_key, style_json, fields_json, visible, published, sort_order, feature_count, byte_size) VALUES ((SELECT id FROM projects WHERE slug = 'urban-digitize'), 'cycleways', 'Cycleways', 'Pistes cyclables', 'geojson/urban-digitize/cycleways.geojson', '{"color": "#8a5a00"}', '["FID", "id"]', 1, 1, 2, 0, 42);
INSERT OR IGNORE INTO layers (project_id, slug, label_en, label_fr, r2_key, style_json, fields_json, visible, published, sort_order, feature_count, byte_size) VALUES ((SELECT id FROM projects WHERE slug = 'urban-digitize'), 'pavements', 'Pavements', 'Revêtements', 'geojson/urban-digitize/pavements.geojson', '{"color": "#f2fc3a"}', '["FID", "id"]', 1, 1, 3, 21, 15406);
INSERT OR IGNORE INTO layers (project_id, slug, label_en, label_fr, r2_key, style_json, fields_json, visible, published, sort_order, feature_count, byte_size) VALUES ((SELECT id FROM projects WHERE slug = 'urban-digitize'), 'roads', 'Roads', 'Routes', 'geojson/urban-digitize/roads.geojson', '{"color": "#2098d8"}', '["FID", "id"]', 1, 1, 4, 9, 14030);
INSERT OR IGNORE INTO layers (project_id, slug, label_en, label_fr, r2_key, style_json, fields_json, visible, published, sort_order, feature_count, byte_size) VALUES ((SELECT id FROM projects WHERE slug = 'urban-digitize'), 'signalisation-horizontale', 'Horizontal Signage', 'Signalisation routière horizontale', 'geojson/urban-digitize/signalisation-horizontale.geojson', '{"color": "#c00e99"}', '["FID", "FID_1", "id"]', 1, 1, 5, 64, 22230);
INSERT OR IGNORE INTO projects (slug, title_en, title_fr, desc_en, desc_fr, category, year, color, visible, collapsed, sort_order, published) VALUES ('legacy-tests', 'Legacy Test Layers', 'Couches de test', 'Early demo layers kept unpublished.', 'Couches de démonstration non publiées.', 'Demo', '2024', '#2098d8', 1, 1, 99, 0);
INSERT OR IGNORE INTO layers (project_id, slug, label_en, label_fr, r2_key, style_json, fields_json, visible, published, sort_order, feature_count, byte_size) VALUES ((SELECT id FROM projects WHERE slug = 'legacy-tests'), 'lidar-survey-blocks', 'LiDAR Classification — Survey Blocks', 'Classification LiDAR — Blocs de relevé', 'geojson/legacy-tests/lidar-survey-blocks.geojson', '{"color": "#f01616"}', '[]', 1, 0, 1, 3, 1049);
INSERT OR IGNORE INTO layers (project_id, slug, label_en, label_fr, r2_key, style_json, fields_json, visible, published, sort_order, feature_count, byte_size) VALUES ((SELECT id FROM projects WHERE slug = 'legacy-tests'), 'fiber-network', 'Fiber Optic Network — Routes', 'Réseau Fibre Optique — Tronçons', 'geojson/legacy-tests/fiber-network.geojson', '{"color": "#19C9EB"}', '[]', 1, 0, 2, 3, 752);
INSERT OR IGNORE INTO layers (project_id, slug, label_en, label_fr, r2_key, style_json, fields_json, visible, published, sort_order, feature_count, byte_size) VALUES ((SELECT id FROM projects WHERE slug = 'legacy-tests'), 'urban-digitization', 'Urban Digitization (v1)', 'Numérisation urbaine (v1)', 'geojson/legacy-tests/urban-digitization.geojson', '{}', '[]', 1, 0, 3, 5, 1200);
INSERT OR IGNORE INTO pointclouds (slug, title_en, title_fr, desc_en, desc_fr, bucket, prefix, status, published) VALUES ('las-1', 'LAS 1', 'LAS 1', 'Point cloud dataset — awaiting upload.', 'Nuage de points — en attente de téléversement.', 'clouds-public', 'las-1/', 'awaiting_upload', 0);

